//Each new term in the Fibonacci sequence is generated by adding
//the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//Find the sum of all the even-valued terms in the sequence
//which do not exceed four million.

var sum = 0
var fib1 = 1
var fib2 = 2

while (fib1 <= 4000000) {
	if(fib1 %2 == 0) {
		sum += fib1
	}
	var temp = fib1
	fib1 = fib2
	fib2 = temp + fib1
}

println(sum)


